# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.CharField(default='gagan', max_length=20),
            preserve_default=False,
        ),
    ]
